# Generated by Django 4.1.1 on 2022-12-29 03:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.CharField(blank=True, max_length=255, verbose_name='CEP'),
        ),
    ]
