# Generated by Django 4.1.1 on 2022-10-02 18:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='projects/images/%Y/%m/%d/', verbose_name='Imagem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', tinymce.models.HTMLField(verbose_name='Descição')),
                ('short_description', models.CharField(max_length=255, verbose_name='Descrição Curta')),
                ('flexible', models.BooleanField(default=True, verbose_name='Flexível')),
                ('goal', models.FloatField(verbose_name='Meta')),
                ('collected', models.FloatField(default=0, verbose_name='Valor Arrecadado')),
                ('deadline', models.DateField(default=datetime.datetime(2022, 10, 3, 15, 19, 20, 392894), verbose_name='Data de Encerramento')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField(verbose_name='Quantia')),
                ('is_payment_approved', models.BooleanField(default=False, verbose_name='Pagamento aprovado?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project', verbose_name='Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
    ]
