# Generated by Django 4.1.1 on 2022-10-02 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='flexible',
        ),
        migrations.AddField(
            model_name='project',
            name='is_flexible',
            field=models.BooleanField(default=True, verbose_name='Aceita doações além da meta?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Está publicado?'),
        ),
    ]
