# Generated by Django 4.1.1 on 2022-10-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição da Imagem'),
        ),
    ]
