# Generated by Django 4.1.1 on 2022-10-16 02:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.FloatField(verbose_name='Objetivo (R$)'),
        ),
    ]
