# Generated by Django 4.1.1 on 2022-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Introdução'),
        ),
    ]
