# Generated by Django 4.1.1 on 2022-10-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='short_description',
            new_name='introduction',
        ),
    ]
