# Generated by Django 4.1.1 on 2022-10-22 21:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_short_description_project_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disapproval_reason',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Motivo da reprovação'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_disapproved',
            field=models.BooleanField(default=False, verbose_name='Reprovado?'),
        ),
    ]
