# Generated by Django 4.1.1 on 2022-12-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_donation_user_alter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_disapproved',
            new_name='is_reproved',
        ),
    ]
