# Generated by Django 4.1.1 on 2022-12-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_is_disapproved_project_is_reproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='disapproval_reason',
            new_name='reproval_reason',
        ),
    ]
