# Generated by Django 4.1.1 on 2022-12-27 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_rename_disapproval_reason_project_reproval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Projeto'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('beneficiary_information', tinymce.models.HTMLField(verbose_name='Informações do Beneficiário')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('comments', tinymce.models.HTMLField(blank=True, verbose_name='Comentários')),
                ('payment_proof', models.FileField(null=True, upload_to='withdrawals/proofs/%Y/%m/%d/', verbose_name='Comprovante da Transferência')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Projeto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
