# Generated by Django 4.1.1 on 2022-12-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_donation_project_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Solicitação de Saque', 'verbose_name_plural': 'Solicitações de Saque'},
        ),
    ]
