# Generated by Django 4.1.1 on 2022-12-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_withdrawalrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='withdrawals/proofs/%Y/%m/%d/', verbose_name='Comprovante da Transferência'),
        ),
    ]
