# Generated by Django 4.1.1 on 2022-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_withdrawalrequest_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='collector_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='id_checkout',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_infos',
            field=models.JSONField(default=None, null=True),
        ),
    ]
