# Generated by Django 4.1.1 on 2022-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_rename_content_messagevote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevote',
            name='value',
            field=models.BooleanField(default=True, verbose_name='Gostou'),
        ),
    ]
